absolutePlot: true
base_dir: .
batch_around_ped: 256
batch_size: 8
clip: 1
config: ./output/eth/star//config_test.yaml
dataset: eth5
ifsave_results: false
ifshow_detail: true
learning_rate: 0.0015
load_model: '201'
model: star.STAR
model_dir: ./output/eth/star/
neigPlot: true
neighbor_thred: 10
num_epochs: 400
obs_length: 8
phase: test
pred_length: 12
randomRotate: true
sample_num: 20
save_base_dir: ./output/
save_dir: ./output/eth/
seq_length: 20
show_step: 100
start_test: 10
test_batch_size: 4
test_set: eth
train_model: star
using_cuda: true
